export const OTHELLO_BOARD = {
  rows: [
    {
      number: 1,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4 },
        { number: 5 },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 2,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4 },
        { number: 5 },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 3,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4 },
        { number: 5 },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 4,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4, color: "black" },
        { number: 5, color: "white" },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 5,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4, color: "white" },
        { number: 5, color: "black" },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 6,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4 },
        { number: 5 },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 7,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4 },
        { number: 5 },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
    {
      number: 8,
      cells: [
        { number: 1 },
        { number: 2 },
        { number: 3 },
        { number: 4 },
        { number: 5 },
        { number: 6 },
        { number: 7 },
        { number: 8 },
      ],
    },
  ],
}
